In [1]:
import numpy as np
import ransac as RS
%load_ext autoreload
%autoreload 2

In [2]:
input_columns = [0]
output_columns = [1]
debug = False
model = RS.LinearLeastSquaresModelWithIntercept(input_columns,output_columns,debug=debug)

In [3]:
numDataPoints = 10
true_data = np.vstack([i, 2*i+1.0] for i in xrange(numDataPoints))
outliers= np.array([[1,10],[2,20]])
all_data = np.vstack([true_data, outliers])
print all_data

[[  0.   1.]
 [  1.   3.]
 [  2.   5.]
 [  3.   7.]
 [  4.   9.]
 [  5.  11.]
 [  6.  13.]
 [  7.  15.]
 [  8.  17.]
 [  9.  19.]
 [  1.  10.]
 [  2.  20.]]
[[  0.   1.]
 [  1.   3.]
 [  2.   5.]
 [  3.   7.]
 [  4.   9.]
 [  5.  11.]
 [  6.  13.]
 [  7.  15.]
 [  8.  17.]
 [  9.  19.]
 [  1.  10.]
 [  2.  20.]]


In [5]:
A,B = model.constructAB(all_data)
print A
print "np.shape(A)", np.shape(A)
print B
modelCoeffs = np.array([1.0,2.0])
B_fit = np.dot(A,modelCoeffs)
print B_fit
D = np.reshape(B_fit,np.shape(B))
C = B - D
print C
print "np.shape(C)", np.shape(C)

[[ 1.  0.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1.  1.]
 [ 1.  2.]]
np.shape(A) (12, 2)
[[  1.]
 [  3.]
 [  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 15.]
 [ 17.]
 [ 19.]
 [ 10.]
 [ 20.]]
[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.   3.   5.]
[[  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  7.]
 [ 15.]]
np.shape(C) (12, 1)
[[ 1.  0.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1.  1.]
 [ 1.  2.]]
np.shape(A) (12, 2)
[[  1.]
 [  3.]
 [  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 15.]
 [ 17.]
 [ 19.]
 [ 10.]
 [ 20.]]
[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.   3.   5.]
[[  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  7.]
 [ 15.]]
np.shape(C) (12, 1)


In [6]:
modelCoeffs = model.fit(all_data)
modelCoeffs = np.array([1.0,2])
print modelCoeffs
error = model.get_error(all_data, modelCoeffs)
print error

[ 1.  2.]
[[  1.]
 [  3.]
 [  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 15.]
 [ 17.]
 [ 19.]
 [ 10.]
 [ 20.]]
[[  1.]
 [  3.]
 [  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 15.]
 [ 17.]
 [ 19.]
 [  3.]
 [  5.]]
[[  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  7.]
 [ 15.]]
[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   49.  225.]
[ 1.  2.]
[[  1.]
 [  3.]
 [  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 15.]
 [ 17.]
 [ 19.]
 [ 10.]
 [ 20.]]
[[  1.]
 [  3.]
 [  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 15.]
 [ 17.]
 [ 19.]
 [  3.]
 [  5.]]
[[  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  7.]
 [ 15.]]
[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   49.  225.]


In [ ]:
ransac_fit, ransac_data = RS.ransac(all_data, model,2,10,0.1,4, return_all=True)
print ransac_fit
print ransac_data

In [ ]:
ransac_data['inliers']

In [ ]:
data = all_data
input_columns = [0,1]
A = data[:, input_columns]
numDataPoints = np.shape(data)[0]
constantTerm = np.ones((numDataPoints,1))
A = np.hstack([constantTerm, A])
print A

In [ ]:
np.random.random(10) - 0.5

In [ ]:
a = np.array([1,0,0])
b = np.array([0,0,1])
